### PR TITLE
Updates to be compatible with astropy.coordinates in v2.0

### LINKED ISSUE #306: Incompatibilities with astropy 2.0
The latest coordinate improvements in astropy v2.0 means a few failures in astroplan. Currently they just show up in the dev build, but I'm about to update the CI tags of "stable" and "LTS" to point to 2.0 meaning that all of jobs in the travis matrix will start to fail.

### PR DESCRIPTION
**Pull request by adrn**
Fixes #306.

### CODE REVIEW

**Comment by bmorris3** [comment]
Thanks @adrn. Do you understand the errors that have occurred, all of the form: 
```
AttributeError: 'numpy.ndarray' object has no attribute '_set_unit'
```

**Comment by adrn** [comment]
I remember seeing that before - I think related to the changes to Numpy array subclassing. Will take a look later and see if I can fix in this PR

**Comment by adrn** [comment]
I don't know exactly what change is causing the failure, but [this is the offending line](https://github.com/astropy/astroplan/blob/master/astroplan/scheduling.py#L148). It appears that in one of the `test_scorer` tests, `AirmassConstraint` returns a dimensionless Quantity, and doing `array *= dimensionless quantity` is now failing. I think this may actually a bug, but we should ask @mhvk.

For now, it looks like this stems from the fact that `AltAz.secz` returns a dimensionless quantity. So, I just get the `.value` from that - will see when CI runs whether this is enough to fix the failures.

**Comment by adrn** [comment]
I take it back - I'm confused. This appears to work fine with Astropy v2.0 or master:
```python
a = np.arange(10.)
b = np.arange(10.) * u.dimensionless_unscaled
a *= b
```

**Comment by mhvk** [comment]
@adrn - the change is indeed that if a quantity is *not* dimensionless, then `array *= quantity` will now fail. This has become possible with `__array_ufunc__` - before, we had no control and it silently succeeded.
